[phases.setup]
nixPkgs = ["nodejs_18", "npm-9_x"]

[phases.install]
cmds = [
  "cd server && npm ci",
  "cd ../client && npm ci"
]

[phases.build]
cmds = [
  "cd server && npm run build",
  "cd ../client && npm run build"
]

[start]
cmd = "cd server && npm run start"

